# These are supported funding model platforms

github: Vadimych1 Jardan09 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: none # Replace with a single Patreon username
open_collective: none # Replace with a single Open Collective username
ko_fi: none # Replace with a single Ko-fi username
tidelift: none # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: none # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: none # Replace with a single Liberapay username
issuehunt: none # Replace with a single IssueHunt username
otechie: none # Replace with a single Otechie username
lfx_crowdfunding: none # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: https://boosty.to/vadimych1 # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
