name: travel_manager_new
description: Manage your travels
publish_to: 'none'
version: 1.0.1-alpha

environment:
  sdk: '>=3.1.0-262.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  translit: ^2.0.1
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/arrow_back.svg
    - assets/images/png/loginbg.png
    - assets/images/svg/emailicon.svg
    - assets/images/svg/passwordicon.svg
    - assets/images/png/registerbg1.png
    - assets/images/png/registerbg2.png
    - assets/images/svg/usericon.svg
    # - assets/images/svg/pencil.svg
    - assets\images\svg\pencil.svg
    - assets/images/svg/calendar.svg
    - assets/images/svg/location.svg
    - assets/images/svg/warn.svg
    - assets/images/svg/money.svg
    - assets\images\png\main_pages\bg1.jpg
    - assets/images/svg/navbar/home.svg
    - assets/images/svg/navbar/settings.svg
    - assets/images/svg/navbar/travels.svg
    - assets/images/svg/paper_plane.svg
    - assets/images/svg/settings.svg
  fonts:
    - family: Pro
      fonts:
        # - asset: fonts/gotham_pro/black.ttf
        #   weight: 900
        # - asset: fonts/gotham_pro/blackitalic.ttf
        #   weight: 900
        #   style: italic
        # - asset: fonts/gotham_pro/bold.ttf
        #   weight: 700
        # - asset: fonts/gotham_pro/bolditalic.ttf
        #   weight: 700
        #   style: italic
        # - asset: fonts/gotham_pro/italic.ttf
        #   weight: 300
        #   style: italic
        # - asset: fonts/gotham_pro/light.ttf
        #   weight: 200
        # - asset: fonts/gotham_pro/lightitalic.ttf
        #   weight: 200
        #   style: italic
        # - asset: fonts/gotham_pro/medium.ttf
        #   weight: 400
        # - asset: fonts/gotham_pro/mediumitalic.ttf
        #   weight: 400
        #   style: italic
        - asset: fonts/gotham_pro/gothampro.ttf
          
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "D:/BIG_CHALLENGES/2023-2024/App/travel_manager_new/assets/images/icon/icon.jpg"