name: travel_manager_new
description: Manage your travels
publish_to: 'none'
version: 1.0.1-beta

environment:
  sdk: '>=3.1.0-262.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  translit: ^2.0.1
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  timezone: ^0.9.2
  flutter_vector_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.2.0
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/png/loginbg.png
    - assets/images/png/registerbg1.png
    - assets/images/png/registerbg2.png
    - assets/images/svg/warn.svg
    - assets\images\png\main_pages\bg1.jpg
  fonts:
    - family: Pro
      fonts:
        - asset: fonts/gotham_pro/gothampro.ttf
          
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "D:/BIG_CHALLENGES/2023-2024/App/travel_manager_new/assets/images/icon/icon.png"