name: travel_manager_new
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-262.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  translit: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/arrow_back.svg
    - assets/images/png/loginbg.png
    - assets/images/svg/emailicon.svg
    - assets/images/svg/passwordicon.svg
    - assets/images/png/registerbg1.png
    - assets/images/png/registerbg2.png
    - assets/images/svg/usericon.svg
